version: '3.8'

services:
  quotes-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=:8080
      - DATABASE_URL=postgres://quotes_user:quotes_pass@postgres:5432/quotes_db?sslmode=disable
      - LOG_LEVEL=info
      - DB_MAX_OPEN_CONNS=50
      - DB_MAX_IDLE_CONNS=25
      - DB_CONN_MAX_LIFETIME=10m
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=quotes_db
      - POSTGRES_USER=quotes_user
      - POSTGRES_PASSWORD=quotes_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quotes_user -d quotes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local